# MongoDB 
MONGO_USERNAME = "MONGO_USERNAME"
MONGO_PASS = "MONGO_PASS"
MONGO_CLUSTER = "MONGO_CLUSTER"
MONDO_DB = 'MONDO_DB'
MONGO_COLLECTION = "MONGO_COLLECTION"
MONGO_URI = "MONGO_URI"

# Speech Service
SPEECH_KEY = "SPEECH_KEY"
SPEECH_REGION = "SPEECH_REGION"

# Language Service
LANGUAGE_UNDERSTANDING_KEY = "LANGUAGE_UNDERSTANDING_KEY"
LANGUAGE_UNDERSTANDING_SUBSCRIPTION = "LANGUAGE_UNDERSTANDING_SUBSCRIPTION"
LANGUAGE_UNDERSTANDING_ENDPOINT = "LANGUAGE_UNDERSTANDING_ENDPOINT"
LANGUAGE_UNDERSTANDING_REGION = "LANGUAGE_UNDERSTANDING_REGION"
CLU_PROJECT_NAME = "CLU_PROJECT_NAME"
CLU_DEPLOYMENT_NAME = "CLU_DEPLOYMENT_NAME"

# Translator Resource (free tier has 2M per month)
TRANSLATOR_KEY = "TRANSLATOR_KEY"
TRANSLATOR_ENDPOINT = "TRANSLATOR_ENDPOINT"
TRANSLATOR_REGION = "TRANSLATOR_REGION"

# Keyword/Wake Word recognition
KEYWORD_RECOGNITION_MODEL = "KEYWORD_RECOGNITION_MODEL"
KEYWORD = "hey class buddy"
